version: '3.8'

services:
  app-dev:
    image: node:18
    container_name: alai-webpage-converter-dev
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3001:3000"
    command: sh -c "npm install && npm run dev"
    environment:
      - NODE_ENV=development
    env_file:
      - .env
